title: Site Title

main_navigation:
  cta_text: Contact Me
  cta_path: "#"
  items:
  - text: Portfolio
    path: "#portfolio"
  - text: About
    path: "#about"

styles:
  colors:
    primary: "#000"

collections:
  projects:

sass:
  style: compressed

plugins:
  - jekyll-paginate

paginate: 5

