title: Site Title

main_navigation:
  cta_path: "#"
  cta_text: Contact Me
  items:
  - text: Portfolio
    path: "#portfolio"
  - text: About
    path: "#about"

hero:
  cta_path: "#about"
  cta_text: Learn More
  description: Great at finding solutions that work.  Not so great at swimming.
  subtitle: would-be nun turned designer
  title: Ophelia

portfolio:
  title: Portfolio
  

styles:
  colors:
    primary: "#000"

collections:
  projects:

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules
exclude: []

plugins:
  - jekyll-paginate

paginate: 5

