title: Site Title

main_navigation:
  cta_path: "#"
  cta_text: Contact Me
  items:
  - text: About
    path: "/#about"
  - text: Portfolio
    path: "/#portfolio"
  site_name: "JER"

hero:
  background: url('/assets/img/hero.jpg')
  cta_path: "#about"
  cta_text: Learn More
  description: Great at finding solutions that work.  Not so great at swimming.
  subtitle: would-be nun turned designer
  title: Ophelia

portfolio:
  title: Portfolio

about:
  image: /assets/img/profile.png
  title: About Me
  description: >
    I make <strong>more working mockups</strong> of working websites and 
    applications than any other designer working today.
  # skills:
  #   - Prototyping animation
  #   - Wireframe creation
  #   - Story-based design
  #   - Web-app design
  #   - Web-site design

# It is recommended that you use Formspree to
# handle contact form submissions on your site
contact:
  form:
    action: https://formspree.io/your@email.com
    email:
      label: Email
      name: _replyto
      error: Please enter a valid email address.
    message:
      label: Message
      name: message
      error: Please leave a message.
    name:
      label: Name
      name: name
      error: Please enter your name.
    phone:
      label: Phone Number
      name: phone
    submit: Send
    thank_you_redirect: /thank_you


  title: Get in Touch

footer:
  owner: Ophelia of Denmark

styles:
  colors:
    background: "#fff"
    primary: "#000"

collections:
  projects:
    output: true
    permalink: /projects/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules
    - css
exclude: []
include: ["_projects"]

plugins:
  - jekyll-paginate

paginate: 5

