title: Site Title

main_navigation:
  cta_path: "#"
  cta_text: Contact Me
  items:
  - text: Portfolio
    path: "#portfolio"
  - text: About
    path: "#about"

hero:
  cta_path: "#about"
  cta_text: Learn More
  description: Great at finding solutions that work.  Not so great at swimming.
  subtitle: would-be nun turned designer
  title: Ophelia

portfolio:
  title: Portfolio

about:
  title: About Me
  description: >
    I make <strong>more working mockups</strong> of working websites and 
    applications than any other designer working today.
  skills:
    - Prototyping animation
    - Wireframe creation
    - Story-based design
    - Web-app design
    - Web-site design

contact:
  title: Get in Touch

styles:
  colors:
    primary: "#000"

collections:
  projects:
    output: true
    permalink: /projects/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: project

sass:
  style: compressed
  load_paths:
    - _sass
    - node_modules
exclude: []
include: ["_projects"]

plugins:
  - jekyll-paginate

paginate: 5

